spring.application.name=fpis-fondrum

spring.datasource.url=jdbc:postgresql://localhost:5432/fpis_fondrum
spring.datasource.username=admin
spring.datasource.password={{pass}}

spring.jpa.hibernate.ddl-auto=update